<a href="https://colab.research.google.com/github/gbasilis/demiurgo/blob/master/Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello this is word")
import numpy as np

print("NumPy version: " + str(np.__version__))

a = np.arange(15).reshape(3, 5)
print(a)

print("\n\n")

c = np.arange(12).reshape(3,4)
b = c > 4
print("b is a boolean with a's shape")
print(b)                                          # b is a boolean with a's shape

print("\n")
print("1d array with the selected elements")

print(c[b])                                       # 1d array with the selected elements


hello this is word
NumPy version: 1.26.4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



b is a boolean with a's shape
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


1d array with the selected elements
[ 5  6  7  8  9 10 11]
