In [6]:
import numpy as np

# Crear una matriz 2x2
matriz_a = np.array([[1, 2], [3, 4]])
print("Matriz A:")
print(matriz_a)

# Crear otra matriz 2x2
matriz_b = np.array([[5, 6], [7, 8]])
print("\nMatriz B:")
print(matriz_b)

# Sumar las matrices
suma = matriz_a + matriz_b
print("\nSuma de A y B:")
print(suma)

# Multiplicar las matrices
producto = np.dot(matriz_a, matriz_b)
print("\nProducto de A y B:")
print(producto)

# Transponer la matriz A
transpuesta_a = np.transpose(matriz_a)
print("\nTranspuesta de A:")
print(transpuesta_a)

# Calcular el determinante de la matriz A
determinante_a = np.linalg.det(matriz_a)
print("\nDeterminante de A:")
print(determinante_a)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Suma de A y B:
[[ 6  8]
 [10 12]]

Producto de A y B:
[[19 22]
 [43 50]]

Transpuesta de A:
[[1 3]
 [2 4]]

Determinante de A:
-2.0000000000000004
